spring.datasource.url=jdbc:postgresql://localhost:5432/furbo_db
spring.datasource.username=postgres
spring.datasource.password=Postgre.00
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=9a9b9c9d9e9f9a9b9c9d9e9f9a9b9c9d9e9f9a9b9c9d9e9f9a9b9c9d9e9f
jwt.expiration=3600000
football-data.api-key=212d906e50c44ce89789ec6b07de8179
