name: Tests

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./TP-Furbo

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Dar permisos a Gradle
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

      # SonarCloud
      # - name: SonarCloud
      #   run: TP-Furbo/gradlew sonar